version: '3.4'
services:

  nginx:
    restart: unless-stopped
    image: "nginx"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/ssl:/etc/nginx/ssl:ro
      - ./data/nginx/log/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    # command: [ 'nginx-debug', '-g', 'daemon off;']

  gunicorn:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
      - ./data/gunicorn/logs:/var/log/pentest-studio/
      - ./data/gunicorn/static:/static
    depends_on:
      - postgres

  worker:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
      - ./data/gunicorn/logs:/var/log/pentest-studio/
      - ./data/gunicorn/static:/static
    entrypoint: /usr/local/bin/celery -A pentest_studio worker -l info

  redis:
    image: "redis"
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - .env